version: '3.4'

services:
  practiceapp:
    image: practiceapp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      REACT_APP_URL: ${REACT_APP_URL}
      REACT_APP_API_KEY: ${REACT_APP_API_KEY}
    ports:
      - 3000:3000
