version: '3.4'

services:
  practiceapp:
    image: component-tests
    build:
      context: .
      target: test
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      REACT_APP_URL: ${REACT_APP_URL}
      REACT_APP_API_KEY: ${REACT_APP_API_KEY}
    command: [ "npm", "test" ]
